export const projectsRoutes = [
  { id: "1", title: "Project 1", description: "Description for Project 1" },
  { id: "2", title: "Project 2", description: "Description for Project 2" },
  { id: "3", title: "Project 3", description: "Description for Project 3" },
  { id: "4", title: "Project 4", description: "Description for Project 4" },
  { id: "5", title: "Project 5", description: "Description for Project 5" },
  { id: "6", title: "Project 6", description: "Description for Project 6" },
  { id: "7", title: "Project 7", description: "Description for Project 7" },
  { id: "8", title: "Project 8", description: "Description for Project 8" },
  { id: "9", title: "Project 9", description: "Description for Project 9" },
  { id: "10", title: "Project 10", description: "Description for Project 10" },
  { id: "11", title: "Project 11", description: "Description for Project 11" },
  { id: "12", title: "Project 12", description: "Description for Project 12" },
  { id: "13", title: "Project 13", description: "Description for Project 13" },
  { id: "14", title: "Project 14", description: "Description for Project 14" },
  { id: "15", title: "Project 15", description: "Description for Project 15" },
  { id: "16", title: "Project 16", description: "Description for Project 16" },
  { id: "17", title: "Project 17", description: "Description for Project 17" },
  { id: "18", title: "Project 18", description: "Description for Project 18" },
  { id: "19", title: "Project 19", description: "Description for Project 19" },
  { id: "20", title: "Project 20", description: "Description for Project 20" },
];
